spring.datasource.url=jdbc:postgresql://localhost:5433/sycophancy_db
spring.datasource.username=postgres
spring.datasource.password=tu_contraseña
spring.datasource.driver-class-name=org.postgresql.Driver

# Generación automática del esquema de la base de datos
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL en consola (útil para desarrollo)
spring.jpa.show-sql=true