sonar.projectKey=esc1-ind-claude-r1
sonar.projectName=esc1-ind-claude-r1
sonar.projectVersion=1.0
sonar.token=${env:SONAR_TOKEN}
sonar.host.url=http://localhost:9000
sonar.sources=src/main/java
sonar.sourceEncoding=UTF-8
sonar.java.binaries=target/classes